In [1]:
from __future__ import division, absolute_import

import os
import sys
import random

import numpy as np
import datetime

#root
absPath = '/home/angela/padding_EBI/'
sys.path.insert(0, absPath)

#from src.Target import Target

np.random.seed(8)
random.seed(8)

from src.preprocessing import *
from src.model_architecture import *
from src.training_model import *
from src.postprocessing import *
from src.comparing_results import *
#from src.callbacks import *
%matplotlib inline

Using TensorFlow backend.


In [2]:
max_lenn = 1000
column = "EC number"
folder = 'EC_number/archaea/3denses/bio_neurons/'

In [3]:
list_padding_short = ['post_padding', 'pre_padding', 'mid_padding', 'strf_padding', 'ext_padding', 
                 'rnd_padding']

#loading data
file_in= "".join([absPath, 'raw_data/uniprot-reviewed_yes+AND+taxonomy_archaea-EC.tab.gz'])
df = loading_data(file_in, column)
#filtering
df_filt = filtering_over_maxlen(df, max_lenn)
dicti = creating_dict()


#processing sequences
dicti_padding = {}
for i in list_padding_short:
    dicti_padding[i] = processing_sequences(df_filt, i, max_lenn)

/home/angela/padding_EBI/src/preprocessing.py:35: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(file_in,compression='gzip',sep='\t')


0        MIIGYFDGLCEPKNPGGIATFGFVIYLDNRKIEGYGLAEKPFSINS...
1        MIIEGEVVSGLGEGRYFLSLPPYKEIFKKILGFEPYEGTLNLKLDR...
2        MNINEILKKLINKSDLEINEAEELAKAIIRGEVPEILVSAILVALR...
3        MVVPLKRIDKIRWEIPKFDKRMRVPGRVYADEVLLEKMKNDRTLEQ...
4        MERAFIEWYPRGYGVAFKIKKKIYEKLSKYQKIEVYETEGFGRLLA...
5        MMMGVELAFPKVVGKQVYGSLYECDEDVLKDTKRLEQIIKEAADIG...
6        MPRLIKDRVPTPERSVGERVRDFGEVNLGYSWELALREAERCLQCP...
7        MGYNEQERAFIEWYPRGYGVGFKVKRRLFETQTEYQRLEIYETEGF...
8        MVDIVKRRDWEKKEKKKIAIERIDTLFTLAERVARYSPDLAKRYVE...
9        MNVEEMKKIAAKEALKFIEDDMVIGLGTGSTTAYFIKLLGEKLKRG...
10       MKKRVVTAGTFDILHPGHYEILKFAKSLGDELIVIVARDETVKKLK...
11       MNNVEKAIEALKKGEIILVYDSDEREGETDMVVASQFITPEHIRIM...
12       MVMVMEKKPYIISNVGMTLDGKLATINNDSRISCEEDLIRVHKIRA...
13       MAVVKEVLEIAEKIKNMEIRGAGKIARSAAYALQLQAEKSKATNVD...
14       MRLSWVIGGAQGTGIDTAANIFGNAVASAGYYIYGNREYYSNIKGG...
15       MAAFTPQWNDWCPGCGNFGILNAEQQAIVELGVDTKNVVVVSGIGC...
16       MVEKFDTIYDYYVDKGYEPSKKRDIIAVFRVTPAEGYTIEQAAGAV.

0        M000000I000000I000000G000000Y000000F000000D000...
1        M0000000I0000000I0000000E0000000G0000000E00000...
2        M00N00I00N00E00I00L00K00K00L00I00N00K00S00D00L...
3        MVVPLKR0IDKIRWE0IPKFDKR0MRVPGRV0YADEVLL0EKMKND...
4        M000E000R000A000F000I000E000W000Y000P000R000G0...
5        M0000000M0000000M0000000G0000000V0000000E00000...
6        M0P0R0L0I0K0D0R0V0P0T0P0E0R0S0V0G0E0R0V0R0D0F0...
7        M00G00Y00N00E00Q00E00R00A00F00I00E00W000Y00P00...
8        M0000000V0000000D0000000I0000000V0000000K00000...
9        M000N000V000E000E000M000K000K000I000A000A000K0...
10       M000000K000000K000000R000000V000000V000000T000...
11       M000N000N000V000E000K000A000I000E000A000L000K0...
12       M000V000M000V000M000E000K000K000P000Y0000I000I...
13       M00A00V00V00K00E00V00L00E00I00A00E00K00I00K00N...
14       MR0LS0WV0IG0GA0QG0TG0ID0TA0AN0IF0GN0AV0AS0AG0Y...
15       M00A00A00F00T00P00Q00W00N00D00W00C00P00G00C00G...
16       M0V0E0K0F0D0T0I0Y0D0Y0Y0V0D0K0G0Y0E0P0S0K0K0R0.

In [4]:
# creating binary enzyme/no enzyme label
df_bin = binarizing_EC(df_filt)

#processing enzyme class label
df_digit1 = first_digit_EC(df_bin)

labels_task1 = bin_to_onehot(df_digit1, 2)

labels_task2 = encoding_as_multilabel(df_digit1, folder)

1.0    10658
0.0     8727
Name: enzyme, dtype: int64
(7,)
Shape of the resulting encoding (19385, 7)


In [5]:
vars_padding = dicti_padding

In [6]:
dicti_padding["post_padding"][1]

array([12,  9,  9,  5,  7,  5, 21, 21, 18,  7, 11,  7,  5,  7, 17, 24,  6,
       11, 18, 11, 15, 15, 24, 10,  5,  9,  6, 10, 10,  9, 11,  7,  6,  5,
       15, 24,  5,  7, 19, 11, 13, 11, 10, 11,  4, 17,  5,  6,  4,  9, 13,
       10,  6, 10, 24,  9,  5, 19,  5,  4,  6,  5,  6, 13,  7, 10, 17,  6,
        6,  7, 21, 10, 21, 11, 15,  9, 10,  9, 11,  9,  7, 13, 10, 10,  9,
        4,  7,  1,  9, 21, 21, 15, 10, 10, 19, 24,  8, 18, 18,  5,  9,  9,
        5,  9,  9,  1, 15, 12, 10, 11, 17,  5, 16,  6, 13, 11, 10,  4,  7,
        4, 21,  9, 10,  9, 11,  9, 10,  7,  4, 10,  4,  5,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [7]:
labels_task1[1]

array([ 0.,  1.], dtype=float32)

In [8]:
labels_task2[1]

array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [9]:
"""creating augmented data from all the types of padding from a specific set of indices"""
#creating idx of the length of data
idx_data = list(range(len(vars_padding['post_padding'])))
#creating empty list for sequences and labels
seqs, lbl_task1, lbl_task2 = [],[],[]

In [10]:
#joining the paddings
for idx in idx_data:
    for padding_type, value in vars_padding.items():
        seqs.append(value[idx]), lbl_task1.append(labels_task1[idx])
        if isinstance(labels_task2, np.ndarray): 
            lbl_task2.append(labels_task2[idx])

In [22]:
len(seqs)

116310

In [11]:
seqs[8]

array([12,  9,  9,  5,  7,  5, 21, 21, 18,  7, 11,  7,  5,  7, 17, 24,  6,
       11, 18, 11, 15, 15, 24, 10,  5,  9,  6, 10, 10,  9, 11,  7,  6,  5,
       15, 24,  5,  7, 19, 11, 13, 11, 10, 11,  4, 17,  5,  6,  4,  9, 13,
       10,  6, 10, 24,  9,  5, 19,  5,  4,  6,  5,  6, 13,  7, 10,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [12]:
lbl_task1[6:13]

[array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32),
 array([ 0.,  1.], dtype=float32)]

In [13]:
lbl_task2[6:15]

[array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.])]

In [14]:
file_idcs_aug = os.path.join(absPath, 'data/', folder, 'idcs_aug_enz.pickle')

with open(file_idcs_aug, "rb") as input_file:
    k_aug_indices = pickle.load(input_file)
    
file_idcs = os.path.join(absPath, 'data/', folder, 'idcs_data_enz.pickle')

with open(file_idcs, "rb") as input_file:
    splitting_sets = pickle.load(input_file)

In [15]:
print(splitting_sets[3][0][0])
print(splitting_sets[3][0][1])
print(splitting_sets[3][0][2])
print(splitting_sets[3][0][3])

4079
10153
10931
14033


In [16]:
vars_padding['post_padding'][4079]

array([12, 21, 10, 21, 13, 21,  9,  6,  8, 18,  9,  8,  7,  8, 19, 24, 10,
       12,  1,  5,  1,  9,  1,  5,  7,  1, 17,  5, 21,  5,  7,  1,  5, 21,
        5,  9, 24, 16, 21, 15,  5, 19, 11, 15, 24,  5, 21, 11,  5, 10, 12,
        7,  1,  9,  5, 19, 10, 13, 11,  6,  1,  8,  9, 15, 21, 21, 19, 17,
       18, 12, 24,  5,  4, 21,  6,  1,  7,  1,  4,  1, 11,  9,  6,  7, 19,
       15, 19, 17, 24,  7, 13, 12, 19,  1, 16, 12, 17, 19, 21,  6,  4,  7,
       11,  7,  7, 11, 22, 18, 17,  4,  1, 11, 21,  7, 10, 21,  7, 18, 21,
        6, 19, 18, 18,  7, 19, 16,  8,  7,  7, 16,  5, 18, 19,  9, 11, 19,
       19,  8, 21, 19, 11, 11,  8, 11,  7, 12,  9,  9, 21,  7, 11, 15, 24,
       18,  5, 19, 17, 16, 17, 17, 12,  4,  5,  9, 19,  7,  7, 18, 15, 24,
        7,  1, 18, 19,  9,  1,  7,  1,  5,  5, 13, 17, 16, 15, 18,  5, 13,
        5, 11,  1, 12,  1, 17, 24, 16,  7, 17,  8, 21, 19, 16,  9,  1, 10,
       10, 11,  9,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0

In [17]:
print(k_aug_indices[3][0][0])
print(k_aug_indices[3][0][1])
print(k_aug_indices[3][0][2])
print(k_aug_indices[3][0][3])

13921
24215
60058
114366


In [19]:
print(len(k_aug_indices[3][0]))
print(len(k_aug_indices[3][1]))
print(len(k_aug_indices[3][2]))

16140
3456
3462


In [20]:
print(len(splitting_sets[3][0]))
print(len(splitting_sets[3][1]))
print(len(splitting_sets[3][2]))

7460
1599
1599


In [21]:
len(vars_padding["post_padding"])

19385

In [ ]:
seqs[13921]

In [36]:
len(vars_padding)

6

In [31]:
from itertools import chain
indices = splitting_sets
k_indices = []
for k_fold in indices:
    i_train, i_val, i_test = k_fold
    print(i_train[0])
    new_i_train = list(chain(*[list(range(x*len(vars_padding),(x*len(vars_padding)+len(vars_padding)))) 
                   for idx,x in enumerate(i_train)]))
    print(new_i_train[0:10])
    new_i_val = list(chain(*[list(range(x*len(vars_padding),(x*len(vars_padding)+len(vars_padding)))) 
                   for idx,x in enumerate(i_val)]))
    new_i_test = list(chain(*[list(range(x*len(vars_padding),(x*len(vars_padding)+len(vars_padding)))) 
                   for idx,x in enumerate(i_test)]))
    random.shuffle(new_i_train), random.shuffle(new_i_val), random.shuffle(new_i_test)
    k_indices.append((new_i_train, new_i_val, new_i_test))      


19046
[114276, 114277, 114278, 114279, 114280, 114281, 104640, 104641, 104642, 104643]
14020
[84120, 84121, 84122, 84123, 84124, 84125, 79410, 79411, 79412, 79413]
14554
[87324, 87325, 87326, 87327, 87328, 87329, 115092, 115093, 115094, 115095]
4079
[24474, 24475, 24476, 24477, 24478, 24479, 60918, 60919, 60920, 60921]
13752
[82512, 82513, 82514, 82515, 82516, 82517, 109290, 109291, 109292, 109293]
10648
[63888, 63889, 63890, 63891, 63892, 63893, 114372, 114373, 114374, 114375]
4262
[25572, 25573, 25574, 25575, 25576, 25577, 107772, 107773, 107774, 107775]
16333
[97998, 97999, 98000, 98001, 98002, 98003, 48222, 48223, 48224, 48225]
13895
[83370, 83371, 83372, 83373, 83374, 83375, 52584, 52585, 52586, 52587]
18071
[108426, 108427, 108428, 108429, 108430, 108431, 12900, 12901, 12902, 12903]


In [35]:
print(len(k_indices[0][0]))
print(len(k_indices[0][1]))
print(len(k_indices[0][2]))

44760
9594
9594


In [27]:
vars_padding["post_padding"][19046]

array([12, 16, 10, 13, 16, 19,  9,  6, 11, 13, 19, 22, 10,  6, 11,  9, 19,
       11,  8, 16, 10, 15, 22, 18, 19,  6,  6, 19, 10,  9, 15,  4,  6, 15,
        8, 21, 11, 11, 10,  4,  9,  1, 10, 21,  7, 21,  7, 11, 21, 18,  7,
        6,  4,  5,  1,  6, 11, 11, 13,  5,  4,  4,  9, 18, 10, 11, 13,  5,
        4,  5, 10, 16, 11,  9, 10, 13,  6, 21, 10,  1, 10, 13,  3, 10, 17,
        6, 21, 21,  5,  7,  6, 21, 16, 24,  9, 11,  9,  5,  4, 13, 11, 10,
        4,  5,  5,  9,  6, 10, 19, 10, 24, 15, 13,  9, 24, 10, 10, 11, 11,
       10,  6, 10,  4, 17, 12,  5, 13, 17, 24, 11, 15, 10, 13, 10, 10, 22,
        6, 13, 22, 16,  1, 11, 17, 13, 24, 10,  6, 11,  9, 10, 13, 11, 13,
       10, 10, 17,  9, 24, 21, 15, 19, 11,  4, 17, 10, 15, 24, 13, 17,  6,
       18, 11,  7,  4,  4,  5, 11, 11, 15, 18,  7,  4, 21,  9,  6,  9, 16,
       15, 24, 13,  4,  4,  4,  9, 24,  6, 11, 11,  7, 24, 11, 13, 18, 18,
        6,  6, 17, 13, 24, 24, 11,  1, 13,  7,  7, 17, 17,  7,  7, 17, 21,
        1,  6, 19, 16, 10

In [30]:
seqs[104643]

array([12,  0,  0, 21,  0,  0, 18,  0,  0,  1,  0,  0,  9,  0,  0, 21,  0,
        0, 11,  0,  0,  1,  0,  0,  7,  0,  0,  7,  0,  0, 24,  0,  0,  1,
        0,  0, 19,  0,  0, 17,  0,  0, 11,  0,  0, 17,  0,  0, 15,  0,  0,
       11,  0,  0, 18,  0,  0, 11,  0,  0, 19,  0,  0, 10,  0,  0, 15,  0,
        0, 10,  0,  0,  1,  0,  0, 11,  0,  0, 11,  0,  0, 15,  0,  0, 21,
        0,  0, 11,  0,  0,  7,  0,  0, 10,  0,  0, 15,  0,  0, 11,  0,  0,
       12,  0,  0,  4,  0,  0, 24,  0,  0, 19,  0,  0, 11,  0,  0, 24,  0,
        0, 18,  0,  0, 11,  0,  0,  1,  0,  0, 18,  0,  0, 18,  0,  0,  4,
        0,  0, 21,  0,  0,  4,  0,  0, 19,  0,  0,  9,  0,  0, 24,  0,  0,
       11,  0,  0, 18,  0,  0, 11,  0,  0, 17,  0,  0, 21,  0,  0, 12,  0,
        0,  1,  0,  0,  4,  0,  0, 10,  0,  0, 21,  0,  0, 11,  0,  0,  4,
        0,  0,  8,  0,  0, 21,  0,  0, 10,  0,  0, 16,  0,  0, 11,  0,  0,
       13,  0,  0, 11,  0,  0, 16,  0,  0, 10,  0,  0, 13,  0,  0,  9,  0,
        0, 21,  0,  0, 18

In [ ]:
#los indices de augmented y los otros no encajan!!!

In [ ]:
k_aug_indices[0]